Repository mad201802/db-tool, pull requests merged in 2023-08, with the labels that each got.

#32 Working table pattern and regex search
  src/main/java/de/dbtool/cli/subcommands/GrepCommand.java
  src/main/java/de/dbtool/database/QueryProcessor.java
  src/main/java/de/dbtool/utils/SearchUtils.java
Labels: jdbc

#33 Feature/listprofiles ascii
  src/main/java/de/dbtool/cli/subcommands/ListProfilesCommand.java
  src/main/java/de/dbtool/utils/TablePrinter.java
Labels: enhancement, cli

#34 Added code coverage and unit tests for CreateProfileCommand
  build.gradle
  src/main/java/de/dbtool/files/ProfileHandler.java
  src/main/java/de/dbtool/utils/FileSystem.java
  src/test/java/de/dbtool/cli/DevelopmentExecution.java
  src/test/java/de/dbtool/cli/subcommands/CreateProfileCommandTests.java
  src/test/java/de/dbtool/cli/subcommands/GrepCommandTests.java
Labels: enhancement

#41 Added simple console printer to support --verbose
  src/main/java/de/dbtool/console/ConsolePrinter.java
Labels: cli

#39 Added value pattern/compare logic, limitRows, limitTextLength
  src/main/java/de/dbtool/DatabaseTests.java
  src/main/java/de/dbtool/cli/subcommands/GrepCommand.java
  src/main/java/de/dbtool/cli/subcommands/ListProfilesCommand.java
  src/main/java/de/dbtool/cli/subcommands/containers/ColumnPatternOption.java
  src/main/java/de/dbtool/cli/subcommands/containers/TablePatternOption.java
  src/main/java/de/dbtool/cli/subcommands/containers/ValueCompareOption.java
  src/main/java/de/dbtool/cli/subcommands/containers/ValuePatternOption.java
  src/main/java/de/dbtool/database/Query.java
  src/main/java/de/dbtool/database/QueryProcessor.java
  src/main/java/de/dbtool/database/interfaces/DefaultDatabase.java
  src/main/java/de/dbtool/database/interfaces/IDatabase.java
  src/main/java/de/dbtool/utils/TablePrinter.java
Labels: cli, jdbc, logic

#48 #47 Implemented `list-tables` command
  src/main/java/de/dbtool/cli/DbToolCommand.java
  src/main/java/de/dbtool/cli/subcommands/ListTablesCommand.java
Labels: enhancement, cli, logic

#50 Wrote all unit tests
  .github/workflows/test.yml
  build.gradle
  src/main/java/de/dbtool/DatabaseTests.java
  src/main/java/de/dbtool/DevExecution.java
  src/main/java/de/dbtool/cli/subcommands/GrepCommand.java
  src/main/java/de/dbtool/cli/subcommands/ListProfilesCommand.java
  src/main/java/de/dbtool/cli/subcommands/ListTablesCommand.java
  src/main/java/de/dbtool/cli/subcommands/processors/ColumnLimitProcessor.java
  src/main/java/de/dbtool/files/ProfileHandler.java
  src/main/java/de/dbtool/utils/ExcludeCoverage.java
  src/test/java/de/dbtool/UnitTestUtils.java
  src/test/java/de/dbtool/cli/subcommands/GrepCommandTests.java
  src/test/java/de/dbtool/cli/subcommands/ListProfilesCommandTests.java
  src/test/java/de/dbtool/cli/subcommands/ListTablesCommandTests.java
Labels: enhancement

#58 fix readme
  README.md
Labels: bug, documentation
